[project]
authors = ["Baichun Sun <baichun.sun@angloamerican.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "backend"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.10.*"
click = ">=8.1.7,<9"
flask = ">=3.1.0,<4"
itsdangerous = ">=2.2.0,<3"
markupsafe = ">=3.0.2,<4"
jinja2 = ">=3.1.4,<4"
werkzeug = ">=3.1.3,<4"
