[project]
authors = ["Baichun Sun <baichun.sun@angloamerican.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "python=3.10"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
